[package]
name = "charl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpiod = "0.2.2"
lcd = "0.4.1"
chrono = "0.4.38"
chrono-tz = "0.10.0"
systemstat = "0.2.3"
